version: '3.3'

services: 

  app-instaltran:
    container_name: 'app-instaltran'
    build: .
    user: node
    working_dir: /usr/src/instaltran
    ports:
      - "127.0.0.70:80:4200"
    volumes:
      - ./instaltran/:/usr/src/instaltran:rw

volumes:
  frontend:
    driver: local